# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Prediction Predictions
description: >-
  Wild guesses about machine learning and AI safety.
baseurl: "" # the subpath of your site, e.g. /blog
url: "z0u.github.io"
show_excerpts: true
header_pages:
  - about.md
  - portfolio.md

# Build settings
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-figure
  - jekyll-mermaid

theme: minima
minima:
  skin: auto
  social_links:
    - title: GitHub
      label: My profile on GitHub
      icon: github
      url: "https://github.com/z0u"
    - title: LinkedIn
      label: My profile on LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/alex-fraser-dev"
    - title: Stack Overflow
      label: My profile on Stack Overflow
      icon: stack-overflow
      url: "https://stackoverflow.com/users/320036/z0r"

# Saas @import is deprecated https://github.com/jekyll/minima/issues/815
sass:
  quiet_deps: true

# https://jekyll-themes.com/jekyll/jekyll-feed
feed:
  excerpt_only: true

mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@10.2.2/dist/mermaid.esm.min.mjs'
